[package]
name = "joltshark"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }

[dev-dependencies]
rstest = "0.26.1"
